version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes: 
      - db_data:/var/lib/postgresql/data/
    env_file: 
      - .env
 
  backend:
    image: ma333da/foodgram_backend
    restart: always
    volumes:
      - static:/app/collectstatic
      - media_value:/app/media
    depends_on:
      - db
    env_file:
      - .env 

  frontend:
    image: ma333da/foodgram_frontend
    volumes:
      - static:/app/result_build
 
  nginx:
    image: ma333da/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/usr/share/nginx/html
      - media_value:/usr/share/nginx/html/media
      - ./docs/:/usr/share/nginx/html/api/docs
    restart: always
    depends_on:
      - backend
      - frontend

 
volumes:
  static:
  media_value:
  db_data:
  # frontend:

