version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes: 
      - db_data:/var/lib/postgresql/data/
    env_file: 
      - .env
 
  backend:
    image: ma333da/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/foodgram/static/
      - media_value:/app/foodgram/media/
    depends_on:
      - db
    env_file:
      - .env 

  frontend:
    image: ma333da/foodgram_frontend
    volumes:
      - frontend:/app/result_build/build/
 
  nginx:
    image: ma333da/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/nginx/html/
      - media_value:/var/html/media/
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - backend
      - frontend

 
volumes:
  static_value:
  media_value:
  db_data:
  frontend:

