MAX_LENGHT = 256
NAME_SIZE = 30
MIN_VALUE = 1
MAX_VALUE = 10


PROHIBITED_USERNAME = 'me'
ROLE_USER = 'user'
ROLE_MODERATOR = 'moderator'
ROLE_ADMIN = 'admin'
MAX_EMAIL_LENGTH = 254
MAX_USERNAME_LENGTH = 150
MAX_NAME_LENGTH = 150
MAX_SLUG_LENGTH = 200
DEFAULT_HEX_COLOR = '#FF0000'