# Generated by Django 3.2.16 on 2026-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': '%(class)ss', 'ordering': ('ingredient',), 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Продукты в рецепте'},
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Аватарка'),
        ),
    ]
