# Generated by Django 3.2.16 on 2026-02-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20260227_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': '%(class)ss', 'ordering': ('ingredient',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты в рецепте'},
        ),
    ]
