# Generated by Django 3.2.16 on 2026-02-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': '%(class)ss', 'ordering': ('ingredient',), 'verbose_name': 'Продукт в рецепте', 'verbose_name_plural': 'Продукты в рецепте'},
        ),
    ]
