# Generated by Django 4.2.25 on 2025-11-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': ('Подписки',), 'verbose_name_plural': 'Подписки'},
        ),
    ]
